version: '3'

services:
  test-web:
    image: python:3.10
    ports:
      - "8888:8888"
    command: python -m http.server 8888
    
  visualization-test:
    image: python:3.10
    ports:
      - "5555:5555"
    command: sh -c "pip install dash plotly && python -c 'import dash; from dash import html; app = dash.Dash(__name__); app.layout = html.Div([html.H1(\"Test Dashboard Working!\")]); app.run_server(host=\"0.0.0.0\", port=5555, debug=False)'"
